### ISSUE TITLE
AttributeError: 'module' object has no attribute 'index_db'

### ISSUE THREAD

**Issue by priesgo** [peterjc/picobio#1]
In line 183, inside a try block it throws this AttributeError that was not catched. Might be a problem with a library... no idea...
In any case, maybe catching AttributeError would be an option as it is a recoverable error.

**Comment by peterjc** [comment]
Hello - apologies I must have missed this issue back in the day.  This is a bit of Biopython, available since Biopython 1.57 released April 2011. From the timing I would guess you were running a slightly too old version? Anyway, I'm going to close this issue now.
